name: webrtsp-clock
base: core22
summary: WebRTSP Clock Server
adopt-info: clock
description: |
  To try, install snap and open http://localhost:5080 in your browser.

license: GPL-3.0
grade: devel
confinement: strict

architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

environment:
  GST_DEBUG: 3
  GST_DEBUG_NO_COLOR: 1
  GST_PLUGIN_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gstreamer-1.0
  GST_PLUGIN_SYSTEM_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gstreamer-1.0
  GST_PLUGIN_SCANNER: $SNAP/usr/libexec/$SNAPCRAFT_ARCH_TRIPLET/gstreamer-1.0/gst-plugin-scanner
  LD_LIBRARY_PATH: $SNAP/opt/${SNAP_NAME}/lib
  FONTCONFIG_PATH: $SNAP/etc/fonts/conf.d
  FONTCONFIG_FILE: $SNAP/etc/fonts/fonts.conf

layout:
  /opt/webrtsp-clock/lib:
    symlink: $SNAP/opt/webrtsp-clock/lib
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts

parts:
  lws:
    plugin: cmake
    source-type: git
    source: https://github.com/warmcat/libwebsockets.git
    source-branch: v4.3-stable
    cmake-parameters:
      - -DLWS_WITHOUT_TESTAPPS=ON
      - -DLWS_WITH_GLIB=ON
      - -DCMAKE_INSTALL_PREFIX=/opt/${SNAPCRAFT_PROJECT_NAME}
    build-packages:
      - libssl-dev
    stage-packages:
      - libssl3
  clock:
    plugin: cmake
    source-type: git
    source: .
    build-environment:
      - PKG_CONFIG_PATH: $SNAPCRAFT_STAGE/opt/${SNAPCRAFT_PROJECT_NAME}/lib/pkgconfig:$SNAPCRAFT_STAGE/opt/${SNAPCRAFT_PROJECT_NAME}/lib/$SNAPCRAFT_ARCH_TRIPLET/pkgconfig:${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/opt/${SNAPCRAFT_PROJECT_NAME}
    override-pull: |
        craftctl default
        craftctl set version="$(git describe --always)"
    after:
      - lws
    build-packages:
      - g++
      - make
      - libspdlog-dev
      - libconfig-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - libmicrohttpd-dev
      - libnice-dev
    stage-packages:
      - libconfig9
      - libslang2
      - libgpm2
      - libpulse0
      - libx264-163
      - libspdlog1
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-nice
      - gstreamer1.0-x
      - fonts-dejavu-core
    prime:
      - -usr/lib/arm-linux-gnueabihf/libde265.so.0.1.1
      - -usr/lib/arm-linux-gnueabihf/libmpeg2.so.0.1.0

apps:
  clock:
    command: opt/${SNAPCRAFT_PROJECT_NAME}/bin/ClockServer
    daemon: simple
    plugs:
      - network-bind
      - network
