name: webrtsp-clock
base: core22
summary: WebRTSP Clock Server
adopt-info: clock
description: |
  To try, install snap and open http://localhost:5080 in your browser.

license: GPL-3.0
grade: devel
confinement: strict

architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

environment:
  GST_DEBUG: 3
  GST_DEBUG_NO_COLOR: 1
  GST_PLUGIN_PATH: $SNAP/opt/${SNAP_NAME}/lib/${SNAPCRAFT_ARCH_TRIPLET}/gstreamer-1.0
  GST_PLUGIN_SYSTEM_PATH: $SNAP/opt/${SNAP_NAME}/lib/${SNAPCRAFT_ARCH_TRIPLET}/gstreamer-1.0
  GST_PLUGIN_SCANNER: $SNAP/opt/${SNAP_NAME}/libexec/gstreamer-1.0/gst-plugin-scanner
  FONTCONFIG_PATH: $SNAP/etc/fonts/conf.d
  FONTCONFIG_FILE: $SNAP/etc/fonts/fonts.conf
  LIBCAMERA_LOG_LEVELS: "*:INFO"

layout:
  /opt/${SNAPCRAFT_PROJECT_NAME}/lib:
    symlink: $SNAP/opt/${SNAPCRAFT_PROJECT_NAME}/lib
  /opt/${SNAPCRAFT_PROJECT_NAME}/share/libcamera:
    symlink: $SNAP/opt/${SNAPCRAFT_PROJECT_NAME}/share/libcamera
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts

parts:
  meson-deps:
    plugin: nil
    override-build: |
      pip install meson
    build-packages:
      - python3-pip
  lws:
    plugin: cmake
    source-type: git
    source: https://github.com/warmcat/libwebsockets.git
    source-branch: v4.3-stable
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DLWS_WITHOUT_TESTAPPS=ON
      - -DLWS_WITH_GLIB=ON
      - -DCMAKE_INSTALL_PREFIX=/opt/${SNAPCRAFT_PROJECT_NAME}
    build-packages:
      - libssl-dev
      - libglib2.0-dev
    stage-packages:
      - libssl3
  gstreamer:
    plugin: meson
    source: https://github.com/RSATom/gstreamer.git
    source-branch: 1.22
    after:
      - meson-deps
    build-packages:
      - ninja-build
      - flex
      - bison
      - nasm
      - libsrtp2-dev
    meson-parameters:
      - --prefix=/opt/${SNAPCRAFT_PROJECT_NAME}
      - -Dauto_features=disabled
      - -Dgpl=enabled
      - -Dgstreamer:ptp-helper-permissions=none
      - -Dbase=enabled
      - -Dgood=enabled
      - -Dgst-plugins-good:rtpmanager=enabled
      - -Dgst-plugins-good:udp=enabled
      - -Dgst-plugins-good:rtp=enabled
      - -Dgst-plugins-good:v4l2=enabled
      - -Dgst-plugins-good:v4l2-probe=true
      - -Dgst-plugins-good:v4l2-libv4l2=auto
      - -Dgst-plugins-good:v4l2-gudev=auto
      - -Dbad=enabled
      - -Dgst-plugins-bad:webrtc=enabled
      - -Dgst-plugins-bad:dtls=enabled
      - -Dgst-plugins-bad:srtp=enabled
      - -Dgst-plugins-bad:videoparsers=enabled
      - -Dugly=enabled
      - -Dgst-plugins-ugly:x264=enabled
      - -Dlibnice=enabled
      - -Dlibnice:gstreamer=enabled
    stage-packages:
      - libgupnp-1.2-1
      - libgupnp-igd-1.0-4
      - libsrtp2-1
  libcamera:
    plugin: meson
    source: https://github.com/raspberrypi/libcamera.git
    after:
      - meson-deps
      - gstreamer
    build-packages:
      - g++
      - ninja-build
      - libyaml-dev
      - python3-yaml
      - python3-ply
      - python3-jinja2
      - libssl-dev
      - openssl
      - libevent-dev
    build-environment:
      - PKG_CONFIG_PATH: $SNAPCRAFT_STAGE/opt/${SNAPCRAFT_PROJECT_NAME}/lib/pkgconfig:$SNAPCRAFT_STAGE/opt/${SNAPCRAFT_PROJECT_NAME}/lib/${SNAPCRAFT_ARCH_TRIPLET}/pkgconfig:${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
    meson-parameters:
      - --prefix=/opt/${SNAPCRAFT_PROJECT_NAME}
      - -Dpipelines=rpi/vc4
      - -Dipas=rpi/vc4
      - -Dv4l2=true
      - -Ddocumentation=disabled
      - -Dtest=false
      - -Dlc-compliance=disabled
      - -Dgstreamer=enabled
      - -Dcam=enabled
      - -Dpycamera=disabled
      - -Dqcam=disabled
      - -Dtracing=disabled
      - -Dudev=disabled
    stage-packages:
      - libevent-2.1-7
      - libevent-pthreads-2.1-7
      - libtiff5
  clock:
    plugin: cmake
    source-type: git
    source: .
    build-environment:
      - PKG_CONFIG_PATH: ${SNAPCRAFT_STAGE}/opt/${SNAPCRAFT_PROJECT_NAME}/lib/pkgconfig:${SNAPCRAFT_STAGE}/opt/${SNAPCRAFT_PROJECT_NAME}/lib/${SNAPCRAFT_ARCH_TRIPLET}/pkgconfig:${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
      - LD_LIBRARY_PATH: $SNAPCRAFT_STAGE/opt/${SNAPCRAFT_PROJECT_NAME}/lib/${SNAPCRAFT_ARCH_TRIPLET}:${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/opt/${SNAPCRAFT_PROJECT_NAME}
    override-pull: |
        craftctl default
        craftctl set version="$(git describe --always)"
    after:
      - lws
      - gstreamer
      - libcamera
    build-packages:
      - g++
      - make
      - libglib2.0-dev
      - libspdlog-dev
      - libconfig-dev
      - libmicrohttpd-dev
      - libssl-dev
    stage-packages:
      - libconfig9
      - libx264-163
      - libspdlog1
      - libmicrohttpd12
      - libssl3
    prime:
      - -usr/lib/arm-linux-gnueabihf/libde265.so.0.1.1
      - -usr/lib/arm-linux-gnueabihf/libmpeg2.so.0.1.0

apps:
  clock:
    command: opt/${SNAPCRAFT_PROJECT_NAME}/bin/ClockServer
    daemon: simple
    plugs:
      - network-bind
      - network
      - camera
      - media-control
      - opengl
    environment:
      LD_LIBRARY_PATH: $SNAP/opt/${SNAP_NAME}/lib:$SNAP/opt/${SNAP_NAME}/lib/${SNAPCRAFT_ARCH_TRIPLET}:$LD_LIBRARY_PATH
